import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptPath = fileURLToPath(import.meta.url);
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');
const required = (env, name) => {
  const value = env[name];
  assert(value, `${name} is required`);
  return value;
};

export function createVisualReviewAttestation(root, env = process.env) {
  const baselineRoot = path.join(root, 'tests/visual/baselines');
  const source = {
    commit: required(env, 'STREAMDOWN_RELEASE_COMMIT'),
    packageSha256: required(env, 'STREAMDOWN_RELEASE_PACKAGE_SHA256'),
  };
  assert(/^[a-f0-9]{40}$/.test(source.commit), 'STREAMDOWN_RELEASE_COMMIT must be 40 lowercase hex characters');
  assert(/^[a-f0-9]{64}$/.test(source.packageSha256), 'STREAMDOWN_RELEASE_PACKAGE_SHA256 must be 64 lowercase hex characters');
  assert.equal(required(env, 'GITHUB_JOB'), 'visual-review', 'Visual review attestation must run in the visual-review job');
  assert.equal(required(env, 'STREAMDOWN_EVIDENCE_ENVIRONMENT'), 'release-evidence-review', 'Visual review attestation requires the separate protected release-evidence-review environment');
  const workflowRef = required(env, 'GITHUB_WORKFLOW_REF');
  assert(/\.github\/workflows\/release-evidence\.yml@refs\/heads\/main$/.test(workflowRef), 'Visual review attestation must run from release-evidence.yml on main');
  const runId = required(env, 'GITHUB_RUN_ID');
  const runAttempt = required(env, 'GITHUB_RUN_ATTEMPT');
  const artifact = {
    name: required(env, 'STREAMDOWN_EVIDENCE_ARTIFACT_NAME'),
    id: required(env, 'STREAMDOWN_EVIDENCE_ARTIFACT_ID'),
    digest: required(env, 'STREAMDOWN_EVIDENCE_ARTIFACT_DIGEST'),
    sourceRunId: required(env, 'STREAMDOWN_EVIDENCE_SOURCE_RUN_ID'),
    sourceRunAttempt: required(env, 'STREAMDOWN_EVIDENCE_SOURCE_RUN_ATTEMPT'),
  };
  assert.equal(artifact.name, 'release-evidence-unreviewed', 'Visual review must consume the immutable unreviewed evidence artifact');
  assert(/^[1-9][0-9]*$/.test(artifact.id), 'STREAMDOWN_EVIDENCE_ARTIFACT_ID must be a positive integer');
  assert(/^[a-f0-9]{64}$/.test(artifact.digest), 'STREAMDOWN_EVIDENCE_ARTIFACT_DIGEST must be a SHA-256 digest');
  assert.equal(artifact.sourceRunId, runId, 'Downloaded evidence must originate from this workflow run');
  assert.equal(artifact.sourceRunAttempt, runAttempt, 'Downloaded evidence must originate from this workflow attempt');

  const manifests = Object.fromEntries(['ios', 'android'].map((platform) => {
    const name = `${platform}.manifest.json`;
    const bytes = fs.readFileSync(path.join(baselineRoot, name));
    const manifest = JSON.parse(bytes);
    assert.equal(manifest.schemaVersion, 2, `${name} must be generated by the current capture tool`);
    assert.deepEqual(manifest.source, source, `${name} must match the publish candidate`);
    assert.equal(Object.hasOwn(manifest, 'review'), false, `${name} must not contain imported reviewer claims`);
    return [name, sha256(bytes)];
  }));
  const artifacts = Object.fromEntries(fs.readdirSync(baselineRoot)
    .filter((name) => name.endsWith('.png')).sort()
    .map((name) => [name, sha256(fs.readFileSync(path.join(baselineRoot, name)))]));
  assert(Object.keys(artifacts).length > 0, 'Visual review attestation requires PNG artifacts');

  const attestation = {
    schemaVersion: 2,
    producer: 'github-actions-protected-review-environment/v2',
    decision: 'environment-approved',
    environment: 'release-evidence-review',
    source,
    matrixSha256: sha256(fs.readFileSync(path.join(root, 'tests/visual/matrix.json'))),
    manifests,
    artifacts,
    evidenceArtifact: artifact,
    workflow: {
      repository: required(env, 'GITHUB_REPOSITORY'),
      ref: workflowRef,
      sha: required(env, 'GITHUB_SHA'),
      runId,
      runAttempt,
      job: 'visual-review',
    },
    createdAt: new Date().toISOString(),
  };
  fs.writeFileSync(path.join(baselineRoot, 'release-review-attestation.json'), `${JSON.stringify(attestation, null, 2)}\n`);
  return attestation;
}

function selfTest() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'streamdown-visual-attest-'));
  try {
    const baselineRoot = path.join(root, 'tests/visual/baselines');
    fs.mkdirSync(baselineRoot, { recursive: true });
    fs.writeFileSync(path.join(root, 'tests/visual/matrix.json'), '{"schemaVersion":1,"cases":[]}\n');
    const source = { commit: 'a'.repeat(40), packageSha256: 'b'.repeat(64) };
    for (const platform of ['ios', 'android']) {
      fs.writeFileSync(path.join(baselineRoot, `${platform}.manifest.json`), JSON.stringify({ schemaVersion: 2, source, artifacts: {} }));
      fs.writeFileSync(path.join(baselineRoot, `${platform}-fixture.png`), `${platform}-patterned-fixture`);
    }
    const env = {
      ...process.env,
      STREAMDOWN_RELEASE_COMMIT: source.commit,
      STREAMDOWN_RELEASE_PACKAGE_SHA256: source.packageSha256,
      STREAMDOWN_EVIDENCE_ENVIRONMENT: 'release-evidence-review',
      STREAMDOWN_EVIDENCE_ARTIFACT_NAME: 'release-evidence-unreviewed',
      STREAMDOWN_EVIDENCE_ARTIFACT_ID: '7',
      STREAMDOWN_EVIDENCE_ARTIFACT_DIGEST: 'c'.repeat(64),
      STREAMDOWN_EVIDENCE_SOURCE_RUN_ID: '42',
      STREAMDOWN_EVIDENCE_SOURCE_RUN_ATTEMPT: '3',
      GITHUB_JOB: 'visual-review',
      GITHUB_REPOSITORY: 'owner/repo',
      GITHUB_WORKFLOW_REF: 'owner/repo/.github/workflows/release-evidence.yml@refs/heads/main',
      GITHUB_SHA: source.commit,
      GITHUB_RUN_ID: '42',
      GITHUB_RUN_ATTEMPT: '3',
      GITHUB_ACTOR: 'automation-is-not-a-reviewer',
    };
    const success = spawnSync(process.execPath, [scriptPath, '--root', root], { env, encoding: 'utf8' });
    assert.equal(success.status, 0, success.stderr);
    const attestation = JSON.parse(fs.readFileSync(path.join(baselineRoot, 'release-review-attestation.json')));
    assert.equal(Object.hasOwn(attestation.workflow, 'actor'), false);
    assert.equal(Object.hasOwn(attestation, 'reviewer'), false);
    fs.rmSync(path.join(baselineRoot, 'release-review-attestation.json'));
    const unprotected = spawnSync(process.execPath, [scriptPath, '--root', root], {
      env: { ...env, STREAMDOWN_EVIDENCE_ENVIRONMENT: 'release-evidence' }, encoding: 'utf8',
    });
    assert.notEqual(unprotected.status, 0);
    assert.match(unprotected.stderr, /separate protected release-evidence-review environment/);
    const wrongArtifact = spawnSync(process.execPath, [scriptPath, '--root', root], {
      env: { ...env, STREAMDOWN_EVIDENCE_ARTIFACT_DIGEST: 'untrusted' }, encoding: 'utf8',
    });
    assert.notEqual(wrongArtifact.status, 0);
    assert.match(wrongArtifact.stderr, /must be a SHA-256 digest/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

if (process.argv[1] === scriptPath) {
  if (process.argv.includes('--self-test')) {
    selfTest();
    console.log('Visual review attestation self-test passed.');
  } else {
    const rootIndex = process.argv.indexOf('--root');
    const root = rootIndex === -1 ? path.resolve(path.dirname(scriptPath), '../..') : path.resolve(process.argv[rootIndex + 1] ?? '');
    if (rootIndex !== -1) assert(process.argv[rootIndex + 1], '--root requires a path');
    createVisualReviewAttestation(root);
  }
}
